### PR TITLE
 Support fully compliant JSON Pointers as well as old style metavalue keys

### PR DESCRIPTION
**Pull request by bpj**
I think I've found a nice way to make `*::Meta*->value` both mostly backwards compatible *and* fully JSON Pointer compliant:

*   Each reference token starts with a forward slash which is followed by zero or more non-slash characters, i.e. it matches the regex `qr{ / [^/]* }msx`.

*   A compliant pointer consists of zero or more such reference tokens.

*   An empty-string `pointer` value means the whole document should be returned.

*   A reference token consisting of a lone forward slash (`/`) is valid and causes the mapping value whose key is an empty string to be returned.

*   The non-compliant part:

    I think the best way to retain as much backward compatibility as possible is to assume that a `pointer` value which starts with any character *except* forward slash is an old-style key, and use it as-is without any JSON Pointer unescaping.  There will still be two edge cases where a key in an old-style program starts with a slash or is an empty string meaning the empty-string key, but that's hard to work around other than putting a warning in the documentation.

Our JSON Pointer use case is a bit different from the canonical use case, since we not only worm into an existing plain data structure but descend into a structure of objects and convert those objects into plain data as we go.  I believe that the best way to do this is to nibble one token at a time from the start of the pointer string, matching one of three possible tokens:

1.  An empty string, matching `qr{ \A\z }msx`, which causes the whole current object to be converted and returned.

2.  A reference token, matching `qr{ \A / ( [^/]* ) }msx`, which causes the value at the mapping key or list index corresponding to the captured part to be returned.

3.  An old-style (backwards compatible) key, matching `qr{ \A [^/] .* \z }msx`, counting the whole string as a mapping key without escapes.

Additionally the rest of the string, which may be empty, is captured into a "next pointer" field for convenience.

The nibbler function receives the caller `*::value` method's options, matches the current pointer against a regex with named captures corresponding to the previous pointer, the current reference token, the current key and the next pointer (the possibly empty rest of the previous pointer) and returns the options as modified/augmented by the named captures of the parser regex, whose names as private/internal values all start with an underscore.

I also added a `strict` option which triggers a mode, probably mainly useful for debugging -- if you get an `undef` back you may want to know why -- although I can see other use cases as well. In this mode the method will `croak` if an invalid pointer, invalid array index, non-existing key or non-existing array index is encountered.  This feature is however easy to remove without affecting the functionality of the rest.

I have updated `metadata.t` to use this syntax, as well as testing the `old-style` syntax where appropriate, and added a `pointer.t` which checks that the examples from [page 5 of RFC 6901](https://tools.ietf.org/html/rfc6901#page-5) work, as well as testing the `strict` mode with valid and invalid data.

I have another enhancement in the works which adds an option which causes `*::Meta*->value` to wrap the contents of MetaString, MetaBool, MetaInlines and/or MetaBlocks in a Span or Div element object with configurable attributes for each kind of meta element -- of course with the MetaString or MetaBool value as a Str element inside the Span.  I want to know what you think about this pointer idea first, since the "wrapper" code needs to be manually integrated with the pointer enhancement code if the latter is adopted.

I also discovered that `Pandoc::Elements`' `use`ing `Pandoc::Metadata` which itself `use`s `Pandoc::Elements` will cause `Pandoc::Metadata`'s imports from `Pandoc::Elements` to be broken, probably because not all the subroutines exported by `Pandoc::Elements` are defined at the time it imports `Pandoc::Metadata`. Replacing `use Pandoc::Metadata ();` with `require Pandoc::Metadata;` solves the problem.

### CODE REVIEW

**Comment by nichtich** [comment]
Thanks. Looks a bit complicated but actually it isn't easy. Not sure about the other enhancement, this sounds to better be put into a custom filter. I'll adjust the documentation and do a release.

**Comment by nichtich** [comment]
Sorry, too quickly. I was just about do to a release, and I did not include the full extension because I need to think about it:  First I see no need of backwards compatibility the preceding `/` should be optional, that's all. Edge cases such as empty strings as keys do not need to  be supported because they are bad practice anyway. Second, I'm not sure if strict mode is actually needed. It needs to be weighted against manageable code.

My opinionated coding style adjustments are on branch https://github.com/nichtich/Pandoc-Elements/tree/extended-json-pointers

**Comment by nichtich** [comment]
Thanks for the code and good arguments, I think you are right. Could it make sense to stick default behavior (croak or just return null) to whether the pointer starts with `/`? Lazy style just-get-me-a-root-value vs. exact lookup? On the other hand you can also traverse the data directly. Best defaults depend on most common use cases which we don't know, do we?

**Comment by bpj** [comment]
I don't think we should conflate the compliant/non-compliant syntax behavior and the return-undef/croak behavior. They are connected only in that they affect the same module and the same set of methods, and thus the code implementing them must consider them both, but from a filter author perspective, and even more from a filter user perspective, I think they are different things.

While it's true that you can debug an error by transforming from the root and dump the tree structure that's less than ideal when you want to deal with an error programmatically. In that case an object with the error parameters is the most module-user friendly: they can check the parameters and either compose their own error message, rethrow the short message or die with the long message (which is the short message plus a stack trace). I agree that croaking by default may be too radical. That's why I propose an option triggering the croaking behavior as a reasonable compromise. However the array based object with hash overloading may be overdoing it. A blessed hashref with `shortmess` and `longmess` as two of the fields and overloaded stringification returning the `shortmess` value should be sufficient. Also the module user may want to include the predefined messages in their own message, in which case it is good if they can be interpolated.

(I'll probably be AFK for most of the weekend, so no rush replying!)

**Pull request merged**
